/*
 * TSM - Temporal Signal Medium
 * Suggests encoding parameters for a given WAV.
 *
 * Copyright (c) 2026 Francesco De Simone
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. A copy is in LICENSE
 * beside this file, and at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Redistributions and derivative works must carry the attribution in NOTICE.
 */

#include "tsm_v5.h"
#include "wav_io_simple.h"
#include "indexed_common.h"

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*
    wav_tsm_advisor_v5_indexed.c

    Generic advisor for v5.1.

    It analyzes a WAV, reports common deltas and zero-like gaps, then creates
    batch files that convert and render using the source WAV sample rate.
*/

static void print_u64(uint64_t value) {
    char text[32];

    tsm5_u64_to_dec(value, text, sizeof(text));
    printf("%s", text);
}

static void fprint_u64(FILE *file, uint64_t value) {
    char text[32];

    tsm5_u64_to_dec(value, text, sizeof(text));
    fprintf(file, "%s", text);
}

static void split_path(
    const char *path,
    char *directory,
    unsigned int directory_size,
    char *base_name,
    unsigned int base_name_size
) {
    const char *slash = strrchr(path, '\\');
    const char *forward = strrchr(path, '/');
    const char *file_part;
    unsigned int len;

    if (forward && (!slash || forward > slash)) {
        slash = forward;
    }

    file_part = slash ? slash + 1 : path;

    if (slash) {
        len = (unsigned int)(slash - path + 1);

        if (len >= directory_size) {
            len = directory_size - 1;
        }

        memcpy(directory, path, len);
        directory[len] = '\0';

    } else {
        snprintf(directory, directory_size, ".\\");
    }

    snprintf(base_name, base_name_size, "%s", file_part);

    {
        char *dot = strrchr(base_name, '.');

        if (dot) {
            *dot = '\0';
        }
    }
}

static void get_exe_directory(
    const char *argv0,
    char *directory,
    unsigned int directory_size
) {
    char unused_base[512];

    split_path(argv0, directory, directory_size, unused_base, sizeof(unused_base));
}

static void write_profile_batch(
    const char *batch_path,
    const char *input_wav,
    const char *bin_dir,
    const char *output_tsm,
    const char *output_wav,
    uint64_t time_unit_ns,
    uint32_t table_count,
    double edge_threshold,
    uint64_t min_delta_ticks,
    double gain,
    double clip_level,
    double zero_threshold,
    double min_zero_ms,
    uint32_t render_sample_rate
) {
    FILE *file = fopen(batch_path, "wb");

    if (!file) {
        fprintf(stderr, "Cannot write batch file: %s\n", batch_path);
        return;
    }

    fprintf(file, "@echo off\r\n");
    fprintf(file, "setlocal\r\n\r\n");

    fprintf(file, "REM Auto-generated by wav_tsm_advisor_v5_indexed.exe\r\n");
    fprintf(file, "REM TSM v5.1: indexed escape + zero-silence segmentation\r\n\r\n");

    fprintf(file, "set \"BIN_DIR=%s\"\r\n", bin_dir);
    fprintf(file, "set \"INPUT=%s\"\r\n", input_wav);
    fprintf(file, "set \"OUTPUT_TSM=%s\"\r\n", output_tsm);
    fprintf(file, "set \"OUTPUT_WAV=%s\"\r\n", output_wav);

    fprintf(file, "set \"TSM_TIME_UNIT_NS=");
    fprint_u64(file, time_unit_ns);
    fprintf(file, "\"\r\n");

    fprintf(file, "set \"TSM_TABLE_COUNT=%u\"\r\n", table_count);
    fprintf(file, "set \"TSM_EDGE_THRESHOLD=%.6f\"\r\n", edge_threshold);

    fprintf(file, "set \"TSM_MIN_DELTA_TICKS=");
    fprint_u64(file, min_delta_ticks);
    fprintf(file, "\"\r\n");

    fprintf(file, "set \"TSM_GAIN=%.6f\"\r\n", gain);
    fprintf(file, "set \"TSM_CLIP_LEVEL=%.6f\"\r\n", clip_level);
    fprintf(file, "set \"TSM_ZERO_THRESHOLD=%.6f\"\r\n", zero_threshold);
    fprintf(file, "set \"TSM_MIN_ZERO_MS=%.3f\"\r\n", min_zero_ms);
    fprintf(file, "set \"TSM_RENDER_SAMPLE_RATE=%u\"\r\n\r\n", render_sample_rate);

    fprintf(file, "echo.\r\n");
    fprintf(file, "echo Creating TSM v5.1 indexed escape profile I%u...\r\n", table_count);
    fprintf(file, "\"%%BIN_DIR%%wav2tsm_indexed_v5.exe\" \"%%INPUT%%\" \"%%OUTPUT_TSM%%\" %%TSM_TIME_UNIT_NS%% %%TSM_TABLE_COUNT%% %%TSM_EDGE_THRESHOLD%% %%TSM_MIN_DELTA_TICKS%% %%TSM_GAIN%% %%TSM_CLIP_LEVEL%% %%TSM_ZERO_THRESHOLD%% %%TSM_MIN_ZERO_MS%%\r\n");
    fprintf(file, "if errorlevel 1 pause & exit /b 1\r\n\r\n");

    fprintf(file, "echo.\r\n");
    fprintf(file, "echo Rendering verification WAV...\r\n");
    fprintf(file, "\"%%BIN_DIR%%tsm2wav_v5.exe\" \"%%OUTPUT_TSM%%\" \"%%OUTPUT_WAV%%\" %%TSM_RENDER_SAMPLE_RATE%% 22000\r\n");
    fprintf(file, "if errorlevel 1 pause & exit /b 1\r\n\r\n");

    fprintf(file, "echo.\r\n");
    fprintf(file, "echo Created:\r\n");
    fprintf(file, "echo %%OUTPUT_TSM%%\r\n");
    fprintf(file, "echo %%OUTPUT_WAV%%\r\n");
    fprintf(file, "echo.\r\n");
    fprintf(file, "pause\r\n");

    fclose(file);
}

static void write_generated_batches(
    const char *argv0,
    const char *input_wav,
    uint64_t time_unit_ns,
    double edge_threshold,
    uint64_t min_delta_ticks,
    double gain,
    double clip_level,
    double zero_threshold,
    double min_zero_ms,
    uint32_t source_sample_rate
) {
    char input_dir[1024];
    char input_base[512];
    char bin_dir[1024];

    unsigned int i;
    const unsigned int table_counts[3] = {4, 8, 16};

    split_path(input_wav, input_dir, sizeof(input_dir), input_base, sizeof(input_base));
    get_exe_directory(argv0, bin_dir, sizeof(bin_dir));

    for (i = 0; i < 3; ++i) {
        unsigned int table_count = table_counts[i];

        char batch_path[1600];
        char output_tsm[1600];
        char output_wav[1600];

        snprintf(batch_path, sizeof(batch_path), "%sTSM_v5_1_I%u_%s.bat", input_dir, table_count, input_base);
        snprintf(output_tsm, sizeof(output_tsm), "%s%s_V5_1_INDEXED_I%u.tsm", input_dir, input_base, table_count);
        snprintf(output_wav, sizeof(output_wav), "%s%s_V5_1_INDEXED_I%u_rendered.wav", input_dir, input_base, table_count);

        write_profile_batch(
            batch_path,
            input_wav,
            bin_dir,
            output_tsm,
            output_wav,
            time_unit_ns,
            table_count,
            edge_threshold,
            min_delta_ticks,
            gain,
            clip_level,
            zero_threshold,
            min_zero_ms,
            source_sample_rate
        );
    }

    {
        char batch_path[1600];
        FILE *file;

        snprintf(batch_path, sizeof(batch_path), "%sTSM_v5_1_profiles_%s.bat", input_dir, input_base);

        file = fopen(batch_path, "wb");

        if (file) {
            fprintf(file, "@echo off\r\n");
            fprintf(file, "setlocal\r\n\r\n");

            fprintf(file, "echo.\r\n");
            fprintf(file, "echo TSM v5.1 indexed escape profiles\r\n");
            fprintf(file, "echo --------------------------------\r\n");
            fprintf(file, "echo 1 - V5_1_INDEXED_I4\r\n");
            fprintf(file, "echo 2 - V5_1_INDEXED_I8\r\n");
            fprintf(file, "echo 3 - V5_1_INDEXED_I16\r\n");
            fprintf(file, "echo.\r\n");
            fprintf(file, "set /p CHOICE=Choose profile: \r\n\r\n");

            fprintf(file, "if \"%%CHOICE%%\"==\"1\" call \"%sTSM_v5_1_I4_%s.bat\"\r\n", input_dir, input_base);
            fprintf(file, "if \"%%CHOICE%%\"==\"2\" call \"%sTSM_v5_1_I8_%s.bat\"\r\n", input_dir, input_base);
            fprintf(file, "if \"%%CHOICE%%\"==\"3\" call \"%sTSM_v5_1_I16_%s.bat\"\r\n", input_dir, input_base);

            fprintf(file, "pause\r\n");
            fclose(file);
        }

        printf("\nGenerated batch files\n");
        printf("---------------------\n");
        printf("%s\n", batch_path);
    }
}

static uint64_t count_zero_like_gaps(
    const WavData *wav,
    double zero_threshold,
    double min_zero_ms
) {
    uint64_t minimum_samples;
    uint64_t i;
    uint64_t count = 0;
    int in_gap = 0;
    uint64_t gap_start = 0;

    minimum_samples =
        (uint64_t)(((double)wav->sample_rate * min_zero_ms / 1000.0) + 0.5);

    if (minimum_samples < 1) {
        minimum_samples = 1;
    }

    for (i = 0; i < wav->sample_count; ++i) {
        int zero = fabs(wav->samples[i]) <= zero_threshold;

        if (zero && !in_gap) {
            in_gap = 1;
            gap_start = i;

        } else if (!zero && in_gap) {
            if (i - gap_start >= minimum_samples) {
                count++;
            }

            in_gap = 0;
        }
    }

    if (in_gap && wav->sample_count - gap_start >= minimum_samples) {
        count++;
    }

    return count;
}

int main(int argc, char **argv) {
    const char *input_wav;

    uint64_t time_unit_ns = 4000;
    double edge_threshold = 0.35;
    uint64_t min_delta_ticks = 1;
    double gain = 8.0;
    double clip_level = 1.0;
    double zero_threshold = 0.03;
    double min_zero_ms = 20.0;

    WavData wav;
    ConditioningStats stats;

    U64List edges;
    U64List deltas;

    DeltaRank *ranks;
    uint64_t rank_count = 0;

    uint64_t i;
    uint64_t top;
    uint64_t zero_gap_count;

    if (argc < 2) {
        printf("Usage:\n");
        printf("  %s input.wav [time_unit_ns] [edge_threshold] [min_delta_ticks] [gain] [clip_level] [zero_threshold] [min_zero_ms]\n", argv[0]);
        return 0;
    }

    input_wav = argv[1];

    if (argc >= 3) time_unit_ns = (uint64_t)strtoull(argv[2], NULL, 0);
    if (argc >= 4) edge_threshold = atof(argv[3]);
    if (argc >= 5) min_delta_ticks = (uint64_t)strtoull(argv[4], NULL, 0);
    if (argc >= 6) gain = atof(argv[5]);
    if (argc >= 7) clip_level = atof(argv[6]);
    if (argc >= 8) zero_threshold = atof(argv[7]);
    if (argc >= 9) min_zero_ms = atof(argv[8]);

    if (!wav_load_pcm16_mono_simple(input_wav, &wav)) {
        return 1;
    }

    condition_signal(&wav, gain, clip_level, &stats);

    u64_list_init(&edges);
    u64_list_init(&deltas);

    detect_edges_schmitt(&wav, time_unit_ns, edge_threshold, min_delta_ticks, &edges);
    build_deltas(&edges, &deltas);

    ranks = make_delta_ranking(&deltas, &rank_count);
    zero_gap_count = count_zero_like_gaps(&wav, zero_threshold, min_zero_ms);

    printf("TSM v5.1 Generic Indexed Advisor\n");
    printf("================================\n\n");

    printf("Input WAV\n");
    printf("---------\n");
    printf("File: %s\n", input_wav);
    printf("Sample rate: %u Hz\n", wav.sample_rate);
    printf("Channels: %u\n", wav.channels);

    printf("Samples: ");
    print_u64(wav.sample_count);
    printf("\n");

    printf("Duration: %.6f seconds\n",
        wav.sample_rate ? (double)wav.sample_count / (double)wav.sample_rate : 0.0
    );

    printf("\nSignal conditioning\n");
    printf("-------------------\n");
    printf("DC offset removed: %.8f\n", stats.dc_offset);
    printf("Peak before gain: %.8f\n", stats.peak_before_gain);
    printf("Gain: %.6f\n", gain);
    printf("Clip level: %.6f\n", clip_level);

    printf("\nTiming\n");
    printf("------\n");
    printf("time_unit_ns: ");
    print_u64(time_unit_ns);
    printf("\n");
    printf("edge_threshold: +/-%.6f\n", edge_threshold);
    printf("min_delta_ticks: ");
    print_u64(min_delta_ticks);
    printf("\n");

    printf("edges: ");
    print_u64(edges.count);
    printf("\n");

    printf("deltas: ");
    print_u64(deltas.count);
    printf("\n");

    printf("\nZero-silence detection\n");
    printf("----------------------\n");
    printf("zero_threshold: %.6f\n", zero_threshold);
    printf("min_zero_ms: %.3f\n", min_zero_ms);
    printf("zero-like gaps: ");
    print_u64(zero_gap_count);
    printf("\n");

    printf("\nMost common deltas\n");
    printf("------------------\n");

    top = rank_count < 32 ? rank_count : 32;

    for (i = 0; i < top; ++i) {
        double percent =
            deltas.count
                ? ((double)ranks[i].count * 100.0) / (double)deltas.count
                : 0.0;

        double microseconds =
            ((double)ranks[i].delta * (double)time_unit_ns) / 1000.0;

        printf("%2u. ", (unsigned int)(i + 1));
        print_u64(ranks[i].delta);
        printf(" ticks = %.3f us : ", microseconds);
        print_u64(ranks[i].count);
        printf(" occurrences (%.2f%%)\n", percent);
    }

    printf("\nRecommended first test\n");
    printf("----------------------\n");
    printf("Use V5_1_INDEXED_I16 first.\n");
    printf("I16 means 15 table entries + raw-delta escape.\n");
    printf("Generated render batches use source sample rate: %u Hz.\n", wav.sample_rate);

    write_generated_batches(
        argv[0],
        input_wav,
        time_unit_ns,
        edge_threshold,
        min_delta_ticks,
        gain,
        clip_level,
        zero_threshold,
        min_zero_ms,
        wav.sample_rate
    );

    free(ranks);
    u64_list_free(&edges);
    u64_list_free(&deltas);
    wav_free_simple(&wav);

    return 0;
}
